"""Regenerate wiki/index.md from markdown files in the wiki directory."""

from __future__ import annotations

from pathlib import Path


def is_meta_wiki_file(path: Path, wiki_root: Path) -> bool:
    """True for auto-managed root files index.md and log.md."""
    try:
        path.resolve().relative_to(wiki_root.resolve())
    except ValueError:
        return False
    if path.name.lower() not in ("index.md", "log.md"):
        return False
    return path.parent.resolve() == wiki_root.resolve()


def _first_heading_and_summary(text: str) -> tuple[str, str]:
    lines = text.strip().splitlines()
    title = ""
    rest_start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("#"):
            title = stripped.lstrip("#").strip()
            rest_start = i + 1
            break
    summary_parts: list[str] = []
    for line in lines[rest_start:]:
        s = line.strip()
        if not s:
            if summary_parts:
                break
            continue
        if s.startswith("#"):
            break
        if s.startswith("---") and not summary_parts:
            continue
        summary_parts.append(s)
        if len(" ".join(summary_parts)) > 200:
            break
    summary = " ".join(summary_parts).strip()
    if len(summary) > 220:
        summary = summary[:217] + "..."
    return title, summary


def regenerate_wiki_index(wiki_dir: Path) -> Path | None:
    """
    Write wiki/index.md with links and one-line summaries for each page.
    Skips root index.md and log.md. Returns path written, or None if wiki missing.
    """
    if not wiki_dir.is_dir():
        return None

    wiki_root = wiki_dir.resolve()
    entries: list[tuple[str, str, str]] = []

    for path in sorted(wiki_dir.rglob("*.md")):
        if is_meta_wiki_file(path, wiki_dir):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        title, summary = _first_heading_and_summary(text)
        rel = path.relative_to(wiki_dir)
        display = title or path.stem
        link = str(rel).replace("\\", "/")
        entries.append((link, display, summary))

    wiki_dir.mkdir(parents=True, exist_ok=True)
    index_path = wiki_dir / "index.md"

    lines = [
        "# Wiki index",
        "",
        "Auto-generated by `py-wikisage compile`. One-line summaries from each page.",
        "",
    ]
    for link, display, summary in entries:
        line = f"- [{display}]({link})"
        if summary:
            line += f" — {summary}"
        lines.append(line)

    if len(entries) == 0:
        lines.append("_No article pages yet._")

    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return index_path
